idf_component_register(
    SRCS
        "app_main.c"
        "cloud/cloud_lm.c"
        "portal/portal.c"
        "storage/storage.c"
        "ui/ui_main.c"
        "ui/ui_home.c"
        "ui/ui_setup.c"
        "ui/fonts/lv_font_georgia_15.c"
        "ui/fonts/lv_font_roboto_16.c"
        "ui/fonts/lv_font_roboto_20.c"
        "ui/fonts/lv_font_roboto_22.c"
        "ui/fonts/lv_font_roboto_28.c"
        "ui/fonts/lv_font_roboto_30.c"
        "ui/fonts/lv_font_roboto_42.c"
        "ui/fonts/lv_font_roboto_56.c"
        "ui/fonts/lv_img_logo.c"
    INCLUDE_DIRS
        "."
        "cloud"
        "portal"
        "storage"
        "ui"
        "ui/fonts"
    REQUIRES
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_http_client
        esp_http_server
        esp_lcd
        mbedtls
        json
        esp_timer
        driver
        lvgl
        lwip
)
